export const Users = [
    {
        id: 1,
        name: 'Muhammad Farhan',
        email: 'farhannisar306@gmail.com',
        password: '123456',
        short_bio: "Test Short Bio",
        avatar: 'https://i.ibb.co/Vw8tBqr/824bd5800350.png',
        about: "I'm a software engineer",
        domain: '@johndoe',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 2,
        name: 'Miftaul Islam Ariyan',
        email: 'miftaulislam005@gmail.com',
        password: '123456',
        short_bio: "Test Short Bio 2",
        avatar: 'https://i.ibb.co.com/Wsj077d/597e9d22564b.jpg',
        about: "I'm a software engineer",
        domain: '@janedoe',
        isActive: true,
        isBlacklisted: false,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 3,
        name: 'Miftaul Islam Ariyan',
        email: 'miftaulislam005@gmail.com',
        password: '123456',
        short_bio: "Test Short Bio 2",
        avatar: 'https://i.ibb.co.com/Wsj077d/597e9d22564b.jpg',
        about: "I'm a software engineer",
        domain: '@janedoe',
        isActive: false,
        isBlacklisted: true,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 4,
        name: 'Miftaul Islam Ariyan',
        email: 'miftaulislam005@gmail.com',
        password: '123456',
        short_bio: "Test Short Bio 2",
        avatar: 'https://i.ibb.co.com/Wsj077d/597e9d22564b.jpg',
        about: "I'm a software engineer",
        domain: '@janedoe',
        isActive: false,
        isBlacklisted: false,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 5,
        name: 'Isshin The Sword Saint',
        email: 'sword_saint@gmail.com',
        password: '123456',
        short_bio: "Hesitation is defeat",
        avatar: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/shadows-die-twice/e/e2/Screen_Shot_2019-04-08_at_1.46.02_AM.jpg',
        about: "The greatest swordsman in the world",
        domain: '@sword_saint',
        isActive: false,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 6,
        name: 'Isshin The Sword Saint',
        email: 'sword_saint@gmail.com',
        password: '123456',
        short_bio: "Hesitation is defeat",
        avatar: 'https://oyster.ignimgs.com/mediawiki/apis.ign.com/shadows-die-twice/e/e2/Screen_Shot_2019-04-08_at_1.46.02_AM.jpg',
        about: "The greatest swordsman in the world",
        domain: '@sword_saint',
        isActive: false,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 7,
        name: 'Emma Watson',
        email: 'emma.watson@gmail.com',
        password: '123456',
        short_bio: "Actress and activist",
        avatar: 'https://randomuser.me/api/portraits/women/1.jpg',
        about: "British actress and UN Women Goodwill Ambassador",
        domain: '@emmawatson',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 8,
        name: 'Chris Evans',
        email: 'chris.evans@gmail.com',
        password: '123456',
        short_bio: "Actor and director",
        avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
        about: "Known for playing Captain America",
        domain: '@chrisevans',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 9,
        name: 'Scarlett Johansson',
        email: 'scarlett.j@gmail.com',
        password: '123456',
        short_bio: "Award-winning actress",
        avatar: 'https://randomuser.me/api/portraits/women/3.jpg',
        about: "Hollywood actress and producer",
        domain: '@scarlettj',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 10,
        name: 'Robert Downey Jr',
        email: 'robert.downey@gmail.com',
        password: '123456',
        short_bio: "Actor and producer",
        avatar: 'https://randomuser.me/api/portraits/men/4.jpg',
        about: "Known for Iron Man role",
        domain: '@robertdowney',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 11,
        name: 'Mark Ruffalo',
        email: 'mark.ruffalo@gmail.com',
        password: '123456',
        short_bio: "Actor and activist",
        avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
        about: "Hollywood actor and environmental activist",
        domain: '@markruffalo',
        isActive: true,
        isBlacklisted: false,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 12,
        name: 'John Doe',
        email: 'john.doe@gmail.com',
        password: '123456',
        short_bio: "Test Short Bio 2",
        avatar: 'https://i.ibb.co.com/Wsj077d/597e9d22564b.jpg',
        about: "I'm a software engineer",
        domain: '@janedoe',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 13,
        name: 'Emma Thompson',
        email: 'emma.thompson@gmail.com',
        password: '123456',
        short_bio: "Award-winning actress",
        avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
        about: "British actress and screenwriter",
        domain: '@emmathompson',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 14,
        name: 'Michael Chen',
        email: 'michael.chen@gmail.com',
        password: '123456',
        short_bio: "Tech entrepreneur",
        avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
        about: "Founder of multiple startups",
        domain: '@michaelchen',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 15,
        name: 'Sarah Williams',
        email: 'sarah.williams@gmail.com',
        password: '123456',
        short_bio: "Digital marketing specialist",
        avatar: 'https://randomuser.me/api/portraits/women/8.jpg',
        about: "Helping brands grow online",
        domain: '@sarahw',
        isActive: false,
        isBlacklisted: true,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 16,
        name: 'David Martinez',
        email: 'david.martinez@gmail.com',
        password: '123456',
        short_bio: "Professional photographer",
        avatar: 'https://randomuser.me/api/portraits/men/9.jpg',
        about: "Capturing life's beautiful moments",
        domain: '@davidm',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 17,
        name: 'Lisa Anderson',
        email: 'lisa.anderson@gmail.com',
        password: '123456',
        short_bio: "Fitness instructor",
        avatar: 'https://randomuser.me/api/portraits/women/10.jpg',
        about: "Helping people achieve their fitness goals",
        domain: '@lisafit',
        isActive: true,
        isBlacklisted: false,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 18,
        name: 'James Wilson',
        email: 'james.wilson@gmail.com',
        password: '123456',
        short_bio: "Financial analyst",
        avatar: 'https://randomuser.me/api/portraits/men/11.jpg',
        about: "Expert in market analysis and investment",
        domain: '@jameswilson',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 19,
        name: 'Maria Garcia',
        email: 'maria.garcia@gmail.com',
        password: '123456',
        short_bio: "Food blogger",
        avatar: 'https://randomuser.me/api/portraits/women/12.jpg',
        about: "Sharing delicious recipes and food stories",
        domain: '@mariaeats',
        isActive: true,
        isBlacklisted: false,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 20,
        name: 'Thomas Brown',
        email: 'thomas.brown@gmail.com',
        password: '123456',
        short_bio: "Software architect",
        avatar: 'https://randomuser.me/api/portraits/men/13.jpg',
        about: "Building scalable solutions",
        domain: '@thomasb',
        isActive: false,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 21,
        name: 'Sophie Turner',
        email: 'sophie.turner@gmail.com',
        password: '123456',
        short_bio: "Game developer",
        avatar: 'https://randomuser.me/api/portraits/women/14.jpg',
        about: "Creating immersive gaming experiences",
        domain: '@sophiet',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 22,
        name: 'Kevin Patel',
        email: 'kevin.patel@gmail.com',
        password: '123456',
        short_bio: "UX designer",
        avatar: 'https://randomuser.me/api/portraits/men/15.jpg',
        about: "Crafting user-centered digital experiences",
        domain: '@kevinp',
        isActive: true,
        isBlacklisted: false,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 23,
        name: 'Rachel Chen',
        email: 'rachel.chen@gmail.com',
        password: '123456',
        short_bio: "Digital Marketing Specialist",
        avatar: 'https://randomuser.me/api/portraits/women/16.jpg',
        about: "Helping brands grow their online presence",
        domain: '@rachelc',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 24,
        name: 'Marcus Johnson',
        email: 'marcus.johnson@gmail.com',
        password: '123456',
        short_bio: "Financial Analyst",
        avatar: 'https://randomuser.me/api/portraits/men/17.jpg',
        about: "Providing strategic financial insights",
        domain: '@marcusj',
        isActive: true,
        isBlacklisted: false,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 25,
        name: 'Emma Wilson',
        email: 'emma.wilson@gmail.com',
        password: '123456',
        short_bio: "Content Creator",
        avatar: 'https://randomuser.me/api/portraits/women/18.jpg',
        about: "Storytelling through digital media",
        domain: '@emmaw',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 26,
        name: 'David Kim',
        email: 'david.kim@gmail.com',
        password: '123456',
        short_bio: "Mobile App Developer",
        avatar: 'https://randomuser.me/api/portraits/men/19.jpg',
        about: "Building innovative mobile solutions",
        domain: '@davidk',
        isActive: false,
        isBlacklisted: true,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 27,
        name: 'Lisa Anderson',
        email: 'lisa.anderson@gmail.com',
        password: '123456',
        short_bio: "HR Consultant",
        avatar: 'https://randomuser.me/api/portraits/women/20.jpg',
        about: "Helping companies build great teams",
        domain: '@lisaa',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 28,
        name: 'James Wilson',
        email: 'james.wilson@gmail.com',
        password: '123456',
        short_bio: "Data Scientist",
        avatar: 'https://randomuser.me/api/portraits/men/21.jpg',
        about: "Turning data into actionable insights",
        domain: '@jamesw',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 29,
        name: 'Sarah Martinez',
        email: 'sarah.martinez@gmail.com',
        password: '123456',
        short_bio: "Graphic Designer",
        avatar: 'https://randomuser.me/api/portraits/women/22.jpg',
        about: "Creating visually stunning designs",
        domain: '@sarahm',
        isActive: true,
        isBlacklisted: false,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 30,
        name: 'Michael Lee',
        email: 'michael.lee@gmail.com',
        password: '123456',
        short_bio: "Product Manager",
        avatar: 'https://randomuser.me/api/portraits/men/23.jpg',
        about: "Driving product innovation",
        domain: '@michaell',
        isActive: false,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 31,
        name: 'Jessica Taylor',
        email: 'jessica.taylor@gmail.com',
        password: '123456',
        short_bio: "Social Media Manager",
        avatar: 'https://randomuser.me/api/portraits/women/24.jpg',
        about: "Building engaging online communities",
        domain: '@jessicat',
        isActive: true,
        isBlacklisted: false,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 32,
        name: 'Ryan Garcia',
        email: 'ryan.garcia@gmail.com',
        password: '123456',
        short_bio: "Cloud Architect",
        avatar: 'https://randomuser.me/api/portraits/men/25.jpg',
        about: "Designing scalable cloud solutions",
        domain: '@ryang',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 33,
        name: 'Emily White',
        email: 'emily.white@gmail.com',
        password: '123456',
        short_bio: "Content Strategist",
        avatar: 'https://randomuser.me/api/portraits/women/26.jpg',
        about: "Crafting compelling content strategies",
        domain: '@emilyw',
        isActive: true,
        isBlacklisted: false,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 34,
        name: 'Daniel Park',
        email: 'daniel.park@gmail.com',
        password: '123456',
        short_bio: "DevOps Engineer",
        avatar: 'https://randomuser.me/api/portraits/men/27.jpg',
        about: "Automating development workflows",
        domain: '@danielp',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 35,
        name: 'Olivia Brown',
        email: 'olivia.brown@gmail.com',
        password: '123456',
        short_bio: "UI Designer",
        avatar: 'https://randomuser.me/api/portraits/women/28.jpg',
        about: "Creating beautiful user interfaces",
        domain: '@oliviab',
        isActive: false,
        isBlacklisted: true,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 36,
        name: 'Christopher Lee',
        email: 'christopher.lee@gmail.com',
        password: '123456',
        short_bio: "Backend Developer",
        avatar: 'https://randomuser.me/api/portraits/men/29.jpg',
        about: "Building robust server applications",
        domain: '@chrisl',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 37,
        name: 'Sophia Rodriguez',
        email: 'sophia.rodriguez@gmail.com',
        password: '123456',
        short_bio: "Digital Artist",
        avatar: 'https://randomuser.me/api/portraits/women/30.jpg',
        about: "Creating digital masterpieces",
        domain: '@sophiar',
        isActive: true,
        isBlacklisted: false,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 38,
        name: 'William Chang',
        email: 'william.chang@gmail.com',
        password: '123456',
        short_bio: "Systems Analyst",
        avatar: 'https://randomuser.me/api/portraits/men/31.jpg',
        about: "Optimizing business systems",
        domain: '@williamc',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 39,
        name: 'Isabella Martinez',
        email: 'isabella.martinez@gmail.com',
        password: '123456',
        short_bio: "SEO Specialist",
        avatar: 'https://randomuser.me/api/portraits/women/32.jpg',
        about: "Improving online visibility",
        domain: '@isabellam',
        isActive: true,
        isBlacklisted: false,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 40,
        name: 'Andrew Wilson',
        email: 'andrew.wilson@gmail.com',
        password: '123456',
        short_bio: "Security Engineer",
        avatar: 'https://randomuser.me/api/portraits/men/33.jpg',
        about: "Protecting digital assets",
        domain: '@andreww',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 41,
        name: 'Victoria Kim',
        email: 'victoria.kim@gmail.com',
        password: '123456',
        short_bio: "Project Manager",
        avatar: 'https://randomuser.me/api/portraits/women/34.jpg',
        about: "Delivering successful projects",
        domain: '@victoriak',
        isActive: true,
        isBlacklisted: false,
        isPremium: true,
        created_at: new Date().toLocaleString(),
    },
    {
        id: 42,
        name: 'Nathan Chen',
        email: 'nathan.chen@gmail.com',
        password: '123456',
        short_bio: "ML Engineer",
        avatar: 'https://randomuser.me/api/portraits/men/35.jpg',
        about: "Developing AI solutions",
        domain: '@nathanc',
        isActive: true,
        isBlacklisted: false,
        isPremium: false,
        created_at: new Date().toLocaleString(),
    }


]